[package]
name = "malm-format-component-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
malm-types = { path = "../malm-types" }
serde.workspace = true

[dev-dependencies]
wit-parser = { version = "=0.236.1", default-features = false }

[lints]
workspace = true
