[package]
name = "malm-format-component-host"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
malm-config = { path = "../malm-config" }
malm-format-component-api = { path = "../malm-format-component-api" }
malm-types = { path = "../malm-types" }
thiserror.workspace = true
wasmparser = { version = "=0.236.1", default-features = false, features = [
  "component-model",
  "features",
  "simd",
  "std",
  "validate",
] }
wasmtime = { version = "=36.0.12", default-features = false, features = [
  "cache",
  "component-model",
  "cranelift",
  "runtime",
  "std",
] }

[dev-dependencies]
wat = { version = "=1.236.1", default-features = false, features = ["component-model"] }
wit-component = { version = "=0.236.1", default-features = false, features = ["dummy-module"] }
wit-parser = { version = "=0.236.1", default-features = false }

[lints]
workspace = true
